# Generated by Django 2.0.6 on 2018-10-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181011_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='picture',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='profesion',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='exerpt',
            field=models.TextField(max_length=2000),
        ),
    ]
