# Generated by Django 2.0.6 on 2018-10-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181011_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(upload_to='icons/'),
        ),
    ]
